#!/usr/bin/env python3
"""judge_holdout_bench -- the judge measured on outputs it was NOT taught.

The adversarial pass on 2026-09-20 was right: judge_bench's "door warm 100%" teaches
the 24 items and then grades the same 24 items. That is a cache-hit measurement (the
cost of the second sighting) and says nothing about accuracy on new work. This is the
measurement the post actually wants to make:

  teach on N labelled rows, grade M HELD-OUT rows of the same shapes, report
    coverage  -- how many held-out judgements the engine answered at all
    accuracy  -- when it answered, how often it was right
    overall   -- accuracy with every `unknown` scored WRONG (never a pass)
  against a floor: a two-line lookup (majority label per criterion-slug + feature
  key) that any honest learned rung must beat (WMF doctrine).

Dataset: tools/eval_cases/cases.jsonl (134 rows / 433 criteria, 79 generated by running
real commands, 55 transcribed from real logs; see its README). Split BY ROW so no
output text appears in both halves; stratified by `shape` so the held-out half carries
the same red/green/looks-red-is-green mix.

  python tools/judge_holdout_bench.py                  # 70/30, seed 7, no brain
  python tools/judge_holdout_bench.py --seeds 5        # mean/min/max over 5 splits
  python tools/judge_holdout_bench.py --brain https://127.0.0.1:8150/v1   # + llm fallback leg

Verdict: the engine rung IS a lookup (tabular, feature-keyed), so without --neural the
bar is "ties the floor" (exit 0) and falling below it is a bug (exit 1). With --neural the
neural rung is fitted on the TRAIN split only and must BEAT the floor -- more coverage at
no worse accuracy, or better accuracy -- for exit 0. Exit 2 when it could not judge.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import tempfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))

CASES_PATH = HERE / "tools" / "eval_cases" / "cases.jsonl"


def load_cases(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        crits = [c for c in r.get("criteria") or [] if isinstance(c.get("label"), bool)]
        if r.get("output") and crits:
            r["criteria"] = crits
            rows.append(r)
    return rows


def split_rows(rows: List[Dict[str, Any]], holdout: float, seed: int) -> Tuple[List, List]:
    """Stratified by shape, BY ROW: an output's text is in one half only."""
    rng = random.Random(seed)
    by_shape: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for r in rows:
        by_shape[str(r.get("shape") or "?")].append(r)
    train, test = [], []
    for shape, group in sorted(by_shape.items()):
        group = list(group)
        rng.shuffle(group)
        k = max(1, int(round(len(group) * holdout))) if len(group) > 1 else 0
        test += group[:k]
        train += group[k:]
    return train, test


class Lookup:
    """The floor: majority label for (criterion slug, feature key), else for the slug
    alone, else abstain. Two lines of logic; a learned rung must beat it."""

    def __init__(self) -> None:
        self.by_key: Dict[Tuple[str, str], Counter] = defaultdict(Counter)
        self.by_slug: Dict[str, Counter] = defaultdict(Counter)

    def teach(self, slug: str, key: str, label: bool) -> None:
        self.by_key[(slug, key)][label] += 1
        self.by_slug[slug][label] += 1

    def predict(self, slug: str, key: str) -> Optional[bool]:
        c = self.by_key.get((slug, key))
        if c:
            return c.most_common(1)[0][0]
        c = self.by_slug.get(slug)
        if c:
            return c.most_common(1)[0][0]
        return None


def score(preds: List[Tuple[Optional[bool], bool]]) -> Dict[str, Any]:
    total = len(preds)
    answered = [(p, t) for p, t in preds if p is not None]
    right = sum(1 for p, t in answered if p == t)
    return {
        "items": total,
        "answered": len(answered),
        "coverage_pct": round(100.0 * len(answered) / max(1, total), 1),
        "accuracy_when_answered_pct": (
            round(100.0 * right / len(answered), 1) if answered else None
        ),
        "overall_pct_unknown_is_wrong": round(100.0 * right / max(1, total), 1),
    }


def train_neural_on(train_rows: List[Dict[str, Any]], ckpt: str) -> Optional[str]:
    """Fit the neural rung on the TRAIN split only (tools/train_neural_rung.py, hashed
    embedder so it needs no fleet) and return the model path, or None. --promote-anyway
    because this is an evaluation artifact, never the served model; the trainer's own
    out-of-distribution gate still applies to the real candidate."""
    import subprocess

    cases = Path(ckpt) / "train_cases.jsonl"
    with open(cases, "w", encoding="utf-8") as fh:
        for r in train_rows:
            fh.write(json.dumps(r) + "\n")
    out = Path(ckpt) / "neural-rung.npz"
    cmd = [sys.executable, str(HERE / "tools" / "train_neural_rung.py"), "--ckpt", ckpt,
           "--cases", str(cases), "--out", str(out), "--embedder", "hashed",
           "--no-holdout-bench", "--promote-anyway", "--json"]
    try:
        subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                       errors="replace", timeout=900)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return str(out) if out.is_file() else None


def run_split(rows, holdout, seed, brain: Optional[str], model: str,
              with_neural: bool = False) -> Dict[str, Any]:
    ckpt = tempfile.mkdtemp(prefix=f"holdout-{seed}-")
    os.environ["AITHER_WM_CKPT_DIR"] = ckpt
    import code_domains  # type: ignore
    import decide  # type: ignore
    import judge as judge_mod  # type: ignore

    if not code_domains._MLP_OK:
        raise RuntimeError("world_model package not importable")

    llm = None
    calls = {"n": 0}
    if brain:
        from judge_bench import LLMJudge  # type: ignore

        lj = LLMJudge(brain, model)

        def llm(prompt: str):  # noqa: E306
            calls["n"] += 1
            crit = prompt.split("Criterion:", 1)[-1].split("\n", 1)[0].strip()
            body = prompt.split("--- output", 1)[-1]
            got = lj.judge(body, [crit])[0]
            return None if got is None else {"answer": "yes" if got else "no", "confidence": 0.6}

    train, test = split_rows(rows, holdout, seed)
    neural_path = train_neural_on(train, ckpt) if with_neural else None
    d = decide.Decider(
        code_domains.DomainEngines(), llm=llm, embed_enabled=False,
        neural_model=Path(neural_path) if neural_path else None,
        neural_enabled=bool(neural_path),
    )
    j = judge_mod.Judge(d)
    dom = f"decide.judge.holdout{seed}"

    floor = Lookup()
    taught = 0
    for r in train:
        for c in r["criteria"]:
            j.teach(r["output"], c["text"], bool(c["label"]), domain=dom)
            floor.teach(
                judge_mod.slug(c["text"]), judge_mod.features(r["output"], c["text"]), bool(c["label"])
            )
            taught += 1

    door_preds: List[Tuple[Optional[bool], bool]] = []
    floor_preds: List[Tuple[Optional[bool], bool]] = []
    srcs: Counter = Counter()
    for r in test:
        crits = [c["text"] for c in r["criteria"]]
        res = j.judge(r["output"], crits, domain=dom)
        for c, v in zip(r["criteria"], res.get("verdicts") or []):
            door_preds.append((v.get("pass"), bool(c["label"])))
            srcs[v.get("source", "?")] += 1
            floor_preds.append(
                (floor.predict(judge_mod.slug(c["text"]), judge_mod.features(r["output"], c["text"])),
                 bool(c["label"]))
            )
    return {
        "seed": seed,
        "train_rows": len(train),
        "test_rows": len(test),
        "taught_criteria": taught,
        "neural_model": neural_path,
        "door": {**score(door_preds), "sources": dict(srcs), "llm_calls": calls["n"]},
        "lookup_floor": score(floor_preds),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cases", default=str(CASES_PATH))
    ap.add_argument("--holdout", type=float, default=0.3)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--seeds", type=int, default=1, help="run N seeds from --seed and aggregate")
    ap.add_argument("--brain", default=None, help="OpenAI-style base URL for an llm fallback leg")
    ap.add_argument("--model", default=os.environ.get("AITHER_BRAIN_MODEL", "default"))
    ap.add_argument("--neural", action="store_true",
                    help="also fit the neural rung on the TRAIN split (hashed embedder) and "
                         "serve it under the engine -- the only leg that can BEAT the floor")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()

    if a.self_test:
        rows = [
            {"output": f"{i} passed\n", "shape": "green",
             "criteria": [{"text": "the test suite passed", "label": True}]} for i in range(6)
        ] + [
            {"output": f"{i} failed\nE  boom\n", "shape": "red",
             "criteria": [{"text": "the test suite passed", "label": False}]} for i in range(6)
        ]
        tr, te = split_rows(rows, 0.3, 1)
        if not (len(te) >= 2 and len(tr) + len(te) == 12):
            print("SELF-TEST FAILED: split")
            return 1
        outs = {r["output"] for r in tr} & {r["output"] for r in te}
        if outs:
            print("SELF-TEST FAILED: an output leaked across the split")
            return 1
        s = score([(True, True), (None, False), (False, True)])
        if not (s["coverage_pct"] == 66.7 and s["accuracy_when_answered_pct"] == 50.0
                and s["overall_pct_unknown_is_wrong"] == 33.3):
            print(f"SELF-TEST FAILED: scoring {s}")
            return 1
        print("SELF-TEST PASSED: row-level split leaks nothing; unknown is scored wrong")
        return 0

    path = Path(a.cases)
    if not path.is_file():
        print(f"COULD NOT JUDGE: no dataset at {path}")
        return 2
    rows = load_cases(path)
    if len(rows) < 30:
        print(f"COULD NOT JUDGE: only {len(rows)} usable rows in {path}")
        return 2

    runs = []
    for s in range(a.seed, a.seed + max(1, a.seeds)):
        try:
            runs.append(run_split(rows, a.holdout, s, a.brain, a.model, with_neural=a.neural))
        except Exception as e:  # noqa: BLE001
            print(f"COULD NOT JUDGE: split seed {s} failed: {type(e).__name__}: {e}")
            return 2

    def agg(key: str, sub: str) -> Dict[str, Any]:
        vals = [r[key][sub] for r in runs if r[key].get(sub) is not None]
        if not vals:
            return {"mean": None}
        return {"mean": round(sum(vals) / len(vals), 1), "min": min(vals), "max": max(vals)}

    report = {
        "dataset": str(path),
        "rows": len(rows),
        "criteria": sum(len(r["criteria"]) for r in rows),
        "holdout": a.holdout,
        "seeds": [r["seed"] for r in runs],
        "runs": runs,
        "door_coverage_pct": agg("door", "coverage_pct"),
        "door_accuracy_when_answered_pct": agg("door", "accuracy_when_answered_pct"),
        "door_overall_pct": agg("door", "overall_pct_unknown_is_wrong"),
        "floor_coverage_pct": agg("lookup_floor", "coverage_pct"),
        "floor_accuracy_when_answered_pct": agg("lookup_floor", "accuracy_when_answered_pct"),
        "floor_overall_pct": agg("lookup_floor", "overall_pct_unknown_is_wrong"),
        "note": "held-out BY ROW, stratified by shape; unknown is scored wrong in *_overall; "
                "the lookup floor is majority label per (criterion, feature key)",
    }
    if a.json:
        print(json.dumps(report, indent=2))
    else:
        r0 = runs[0]
        print(f"{len(rows)} rows / {report['criteria']} criteria; holdout {a.holdout}; "
              f"{len(runs)} seed(s); first split: {r0['train_rows']} train rows, "
              f"{r0['test_rows']} test rows, {r0['taught_criteria']} criteria taught\n")
        print(f"{'leg':22}{'coverage':>10}{'acc|answered':>14}{'overall':>10}")
        door_label = "door (engine+neural)" if a.neural else "door (engine only)"
        for name, key in ((door_label, "door"), ("lookup floor", "lookup_floor")):
            cov = agg(key, "coverage_pct")["mean"]
            acc = agg(key, "accuracy_when_answered_pct")["mean"]
            ovr = agg(key, "overall_pct_unknown_is_wrong")["mean"]
            print(f"{name:22}{cov:>9.1f}%{(acc if acc is not None else 0):>13.1f}%{ovr:>9.1f}%")
        print(f"\nheld-out door sources (seed {r0['seed']}): {r0['door']['sources']}"
              + (f"; llm calls {r0['door']['llm_calls']}" if a.brain else ""))

    d_acc = report["door_accuracy_when_answered_pct"]["mean"]
    f_acc = report["floor_accuracy_when_answered_pct"]["mean"]
    d_cov = report["door_coverage_pct"]["mean"] or 0
    f_cov = report["floor_coverage_pct"]["mean"] or 0
    # The engine rung IS a lookup by construction (tabular, keyed on the feature
    # descriptor), so engine-only is EXPECTED to tie the floor: a tie within half a
    # point is the expectation met, not a miss. What has to BEAT the floor is a
    # learned rung (--neural): more coverage at no worse accuracy, or better accuracy.
    have = d_acc is not None and f_acc is not None
    tie = have and abs(d_acc - f_acc) <= 0.5 and abs(d_cov - f_cov) <= 0.5
    beats = have and (
        (d_cov > f_cov + 0.5 and d_acc >= f_acc - 0.5)
        or (d_acc > f_acc + 0.5 and d_cov >= f_cov - 0.5)
    )
    if d_cov <= 0 or d_acc is None:
        verdict, rc = "held-out door answered nothing", 1
    elif a.neural:
        verdict = ("neural rung BEATS the lookup floor on held-out rows" if beats
                   else "neural rung only TIES the lookup floor -- it adds nothing here" if tie
                   else "neural rung is WORSE than the lookup floor")
        rc = 0 if beats else 1
    else:
        verdict = ("engine ties the lookup floor (expected: the engine IS a lookup)"
                   if tie or beats else "engine is BELOW its own floor -- a bug, not a result")
        rc = 0 if (tie or beats) else 1
    # under --json the verdict goes to stderr so stdout stays one parseable document
    print(("" if a.json else "\n") + "VERDICT: " + verdict,
          file=sys.stderr if a.json else sys.stdout)
    return rc


if __name__ == "__main__":
    sys.exit(main())
